### ISSUE TITLE
Lua Error: string expected, got nil

### ISSUE THREAD

**Issue by StoicaRemus** [jamores/eth-ws-someip#10]
Getting the following error when I try to analyze someIP packets: 'Lua Error : PATH\someip.lua:129: bad argument #3 to '__newindex' (string expected, got nil)' . If needed I will uploaded a packet for analysis.

**Comment by geynis** [comment]
Hi, probably the packet has a wrong message type.
I can add maybe a default type for unknown type number.
Could you please upload the pcap?

Thanks.

**Comment by StoicaRemus** [comment]
Here is a packet sample.
[Lua error.zip](https://github.com/jamores/eth-ws-someip/files/3630322/Lua.error.zip)

**Comment by geynis** [comment]
This packet SOME/IP header is malformed, some fields are 0xFF like the protocol version, also the message type is 0xFF but there no such type. It is true that the code needs to handle the errors. I can have a look maybe next week to see how much is needed to be done.
But anyway you should try to see why you have malformed header.

Cheers.

**Comment by StoicaRemus** [comment]
That cleared things out. Thanks!

**Comment by geynis** [comment]
try the develop branch, should be OK now
https://github.com/jamores/eth-ws-someip/tree/develop

**Comment by StoicaRemus** [comment]
Latest build shows some weird Info, uploading a picture and a packet.
![Capture](https://user-images.githubusercontent.com/27064432/65595694-f8e30d80-df9d-11e9-8007-2b7b1b862716.PNG)
[Offset.zip](https://github.com/jamores/eth-ws-someip/files/3652059/Offset.zip)

Packets might be corrupted?

**Comment by geynis** [comment]
yes your message type is still 0xFF
