### ISSUE TITLE
Error during loading in someip.lua:13: bad argument #1 to 'Proto' (Proto_new: there cannot be two protocols with the same name)

### ISSUE THREAD

**Issue by cfanatic** [jamores/eth-ws-someip#16]
Hi,

I am using Wireshark 3.2.1 on Linux 5.4.0-kali3-amd64 and I was receiving this error during startup after following your installation instructions:

```
Lua: Error during loading:
.local/lib/wireshark/plugins/3.2/eth-ws-someip/someip.lua:13:
bad argument #1 to 'Proto' (Proto_new: there cannot be two protocols with the same name)
stack traceback:
[C]: in function 'Proto'
.local/lib/wireshark/plugins/3.2/eth-ws-someip/someip.lua:13: in main chunk
```

The fix was to replace line 13 in `someip.lua` with the following expression:
```
p_someip = Proto("someip2","Scalable service-Oriented MiddlewarE over IP")
```

Then during packet analysis, Wireshark was throwing an error in line 135 in `sd_options.lua` which was solved by the following fix:
```
if o_l4[l4_u8] == "TCP" then
    DissectorTable.get("tcp.port"):add(buf(offset,2):uint(),Dissector.get("someip2"))
elseif o_l4[l4_u8] == "UDP" then
    DissectorTable.get("udp.port"):add(buf(offset,2):uint(),Dissector.get("someip2"))
end
```

I cannot recall that I have installed a Wireshark SOME/IP plugin before. So I am a bit confused by the errors.

Cheers,
Arnd

**Comment by geynis** [comment]
Hi I think that from Wireshark 3.2 there is a built-in support for SOME/IP.

**Comment by cfanatic** [comment]
Oh really, then I need to check because this built-in support for SOME/IP was not enabled by default in Wireshark. Only thing I saw in the eth0 trace were raw UDP packets. This made me search the Internet and I found your plugin.

**Comment by cfanatic** [comment]
Yup, I was using Wireshark 2.x, in the most recent version there is SOME/IP compatibility. Thanks for the heads-up.
